server:
  http:
    addr: 0.0.0.0:8100
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9100
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(192.168.43.144:3306)/laomadj_customer?parseTime=True&loc=Local
  redis:
    addr: 192.168.43.144:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
